# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "fileshare"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

upload_basedir: 'upload'
share_basedir: 'public/pub'

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
engines:
  template_toolkit:
#     start_tag: '[%'
#     end_tag:   '%]'

session: "cookie"
session_cookie_key: ";G69\[jja1212Z"
session_name: "filesharing"
session_expires: 2h


plugins:
 Auth::Extensible:
  no_default_pages: 1
  no_login_handler: 1
  login_page: '/login'
  realms:
   users:
    provider: Config
    users:
      - user: test  
        pass: beer
        roles:
         - 'admin'
      - user: test2 
        pass: beer
        roles:
         - 'admin'

